### ISSUE TITLE
refs other than heads(branches),tags,hashes

### ISSUE THREAD

**Issue by andreineculau** [winfsp/hubfs#2]
Nice initiative 👏 
I had a look at your source code and just wanted to confirm and highlight that your "ref" seems to only handle `refs/heads/*`, `refs/tags/*` and hashes.
Except there can be other refs. `git notes` command and https://github.com/google/git-appraise store content under `refs/notes`, etc.

**Comment by billziss-gh** [comment]
I discuss below problems and potential solutions:

- Currently HUBFS organizes its namespace in the pattern / _owner_ / _repo_ / _ref_ / _path_ and employs a _ref_ "flattening" scheme. By _ref_ flattening I mean that it merges _ref_'s from `refs/heads` and `refs/tags` and also replaces any slashes (/) with spaces so that `release/1.0` becomes `release+1.0`. (In the current release slashes (/) are replaced with spaces but this will be changed in the next release to avoid problems with spaces in paths.)

    The _ref_ flattening allows HUBFS to quickly determine the "kind" of a path component. For example, in the path `/winfsp/hubfs/master/README.md` HUBFS can quickly determine that `winfsp` is the _owner_, `hubfs` is the _repo_, `master` is the _ref_ and `/README.md` is the path to repository content.

    HUBFS could also support an alternative _ref_ flattening scheme (perhaps when a command line option is supplied). Some example _ref_'s in this proposed scheme follow:

    - branches: `heads+master`
    - tags: `tags+v1.0`
    - notes: `notes+commits`
    - PR's: `remotes+origin+pull+3+head`
    - etc.

    @andreineculau I do not know if this alternative scheme gets you what you need.

- Currently HUBFS can only support _ref_'s that point to commit objects.

**Comment by billziss-gh** [comment]
HUBFS now has a `-fullrefs` option that can be used to make all refs available.

Related commits: 1c74be74ceff3eb60c5e5a7de9bab5405a071b53, 599c0a4646e143d8b9585d46ee51c8d93a039aef
